In [1]:
import jax.numpy as jnp

In [3]:
A = jnp.linspace(0,2,20)

In [10]:
A[jnp.arange(3,5)]

Array([0.31578946, 0.42105263], dtype=float32)

In [11]:
jnp.arange(3,5)

Array([3, 4], dtype=int32)

In [13]:
jnp.cumsum(jnp.array([1,3,5]))

Array([1, 4, 9], dtype=int32)

In [21]:
try:
    x = 1
    y = 0
    assert y != 0, "Invalid Operation"
    print(x / y)
 
# the errror_message provided by the user gets printed 
except AssertionError as msg: 
    print(msg)


Invalid Operation
